import = [
    #"~/.config/alacritty/themes/nightfly.toml"
    "~/.config/alacritty/themes/tokyo-night-storm.toml"
]

[env]
TERM = "xterm-256color"

[font]

size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[window]


opacity = 1

padding.x = 10
padding.y = 10

[selection]
save_to_clipboard = true

